# .github/workflows/pyinstaller-build.yml

name: PyInstaller Build and Release

on:
  push:
    tags:
      - "V*" # Jalankan hanya saat ada tag baru (misal: v1.0, v2.5.1)
  workflow_dispatch: # Memungkinkan untuk menjalankan manual dari tab Actions

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: 1. Check-out repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Sesuaikan dengan versi Python Anda
          cache: "pip"

      - name: 3. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Pastikan pyinstaller dan scikit-learn (untuk hooks numpy) terinstal
          pip install pyinstaller scikit-learn

      - name: 4. Extract Version from Tag
        id: get_version
        shell: bash
        run: |
          # Menghapus 'v' dari nama tag, misal: v1.3.0 -> 1.3.0
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: 5. Create .spec file with correct content
        shell: bash
        run: |
          cat << EOF > main.spec
          # -*- mode: python ; coding: utf-8 -*-
          
          a = Analysis(
              ['main.py'],
              pathex=[],
              binaries=[],
              datas=[
                  ('app', 'app'),
                  ('assets', 'assets')
              ],
              hiddenimports=[
                  'pandas._libs.tslibs.base',
                  'pandas._libs.tslibs.np_datetime',
                  'pandas._libs.tslibs.timedeltas',
                  'matplotlib.backends.backend_tkagg',
                  'sklearn.utils._cython_blas',
                  'PIL._tkinter_finder',
                  'pymupdf.core'
              ],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=['pytest', 'doctest', 'unittest', 'PyQt5', 'PyQt6', 'wx'],
              noarchive=False,
          )
          pyz = PYZ(a.pyz, a.scripts, a.binaries)
          
          exe = EXE(
              pyz,
              a.scripts,
              [],
              exclude_binaries=True,
              name='FileSearchPro',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              runtime_tmpdir=None,
              console=False,
              icon='assets/search_icon.ico',
          )
          
          coll = COLLECT(
              exe,
              a.binaries,
              a.zipfiles,
              a.datas,
              strip=False,
              upx=True,
              name='FileSearchPro'
          )
          EOF

          echo "--- Created main.spec content ---"
          cat main.spec
          echo "---------------------------------"

      - name: 6. Build Executable with PyInstaller
        run: pyinstaller --noconfirm --clean --onefile main.spec

      - name: 7. Set up UPX for compression
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest

      - name: 8. Compress the executable with UPX
        if: matrix.os != 'macos-latest' # UPX sering bermasalah di macOS runner
        run: |
          ls -R dist/
          upx --best --lzma dist/FileSearchPro*

      - name: 9. Prepare Artifacts
        shell: bash
        run: |
          # Tentukan nama file output berdasarkan OS dan versi
          VERSION="${{ env.VERSION }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ARTIFACT_NAME="File-Search-Pro-v${VERSION}-Windows-x64.exe"
            mv dist/FileSearchPro.exe "dist/$ARTIFACT_NAME"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            ARTIFACT_NAME="File-Search-Pro-v${VERSION}-macOS"
            mv dist/FileSearchPro "dist/$ARTIFACT_NAME"
          else
            ARTIFACT_NAME="File-Search-Pro-v${VERSION}-Linux-x64"
            mv dist/FileSearchPro "dist/$ARTIFACT_NAME"
          fi
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: 10. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/${{ env.ARTIFACT_NAME }}

  release:
    name: Create GitHub Release
    needs: build # Jalankan hanya setelah semua job 'build' selesai
    runs-on: ubuntu-latest
    permissions:
      contents: write # Izin untuk membuat rilis

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release of File Content Search Pro.
            Download the appropriate version for your operating system below.
          files: |
            artifacts/*/*
